apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-k0kt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-k0kt
    app.kubernetes.io/part-of: tkrw-pr712-0075-0005-app
  name: devfile-sample-k0kt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-k0kt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-k0kt
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0005-tenant/tkrw-pr712-0075-0005-app/devfile-sample-k0kt@sha256:e6d35b3a93f9ff2e3e56f5c86f31079ebf74519adfa7f8d99455d8d2e52e2e53
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
